apiVersion: apps/v1
kind: Deployment
metadata:
  name: logix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logix-app
  template:
    metadata:
      labels:
        app: logix-app
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/guidedlabs-1686748561004/logix-repo/backend:latest
        ports:
        - containerPort: 8081

